# Generated by Django 2.2.19 on 2021-04-28 17:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Name')),
                ('description', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Price')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
    ]
